version: '3.9'

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - proxy
    restart: unless-stopped

  # Prometheus para monitoreo
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  # Grafana para visualización
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped

  # Node Exporter para métricas del sistema
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: unless-stopped

  # cAdvisor para métricas de contenedores
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
      - /cgroup:/cgroup:ro
      - /etc:/rootfs/etc:ro
    security_opt:
      - no-new-privileges:true
    command:
      - --docker_only
      - --housekeeping_interval=30s
      - --disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl
    networks:
      - monitoring

networks:
  proxy:
    driver: bridge
  monitoring:
    driver: bridge
